### ISSUE TITLE
Navbar links rise a problem 

### ISSUE THREAD

**Issue by boulaffasae** [jamstack-cms/jamstack-ecommerce#16]
When user is not on Homepage `/`, a problem occur in the navbar links. All links link to a misplaced file.

1. Navigate to the **New arrivals** page
2. Now click on another navbar link, such as **Sofas**
3. A **404 page** is showen, `/new-arrivals/sofas` Not Found

## Why the problem occur ?

In the following JavaScript code, 

```js
<Link to={l.link} key={i}>
```

`link` values are missing a `/` prefix. And it render as:

```js
<a href="sofas>
```

## How can we resolve the issue ?

Prefix all links with a `/`.

```js
<Link to={`/${l.link}`} key={i}>
```

**Comment by francispham** [comment]
@boulaffasae I got the same problem as well. I tried but your resolve doesn't work. I found the links work fine when you don't upgrade the package.json and yarn.lock files!

**Comment by boulaffasae** [comment]
Then this might be because of this PR feat(gatsby): Add support for relative links [#24054](https://github.com/gatsbyjs/gatsby/pull/24054)
