### ISSUE TITLE
Stripe API keys are hard-coded

### ISSUE THREAD

**Issue by auchenberg** [jamstack-cms/jamstack-ecommerce#2]
https://github.com/jamstack-cms/jamstack-ecommerce/blob/88a2d489af4204d11d8612b4fb3c24a14321c030/src/pages/checkout.js#L20

**Expected:**
Keys to be loaded from a secure place.

**Comment by kefimochi** [comment]
Agreed! You can create a .env file, add it to gitignore & import all important keys securely from there  🙂
