### ISSUE TITLE
Don't find gatsby

### ISSUE THREAD

**Issue by nabuko81** [jamstack-cms/jamstack-ecommerce#24]
Hello Nader and everyone,

Maybe i'm too dumb, but I follow all the instructions on git and on https://dev.to/aws/building-a-serverless-jamstack-ecommerce-store-with-gatsby-aws-303f, and I dont't find anything about gatsby.

I clone, go to the good directory, npm install, and then I want to do Gatsby develop, and that don't work :'(

npm run dev work perfectly, but really want to have the same things as Nader Dabit

I try npm install -g gatsby-cli, and creata a new project but i cant clone yours in it :'(

So if you can give me some advice, i take it.

Good day to you.
Nab

**Comment by marksteven** [comment]
Hi Nader,
I too have had this issue. 
On closer inspection it appears to not be a Gatsby project?
Do you have the original somewhere else maybe and it got moved?
Like Nabuko I too would like to try this out Gatsby Amplify etc
This is the link to the repository from the page 
https://github.com/jamstack-cms/jamstack-ecommerce
