### ISSUE TITLE
I can't log in to admin or create an account

### ISSUE THREAD

**Issue by mattmaker** [jamstack-cms/jamstack-ecommerce#6]
I followed all the steps in this tutorial: 
https://dev.to/aws/building-a-serverless-jamstack-ecommerce-store-with-gatsby-aws-303f

But when I go to the Admins panel in the bottom right navigation, the Sign Up/ Sign In buttons don't do anything.

I was trying to create an admin account and got the email with a verification code, but when I put the code in, the button didn't do anything. 

Now neither buttons work and I'm not sure why.

I don't know if this will help but here is a screenshot of the console:

![console-screenshot](https://user-images.githubusercontent.com/3858718/78550529-14369d00-77b9-11ea-8bbc-6fcc91d5eee6.png)

Any ideas?

**Comment by pablko** [comment]
I can find the solution, but can add some information.

The _PostConfirmation-dev_ Lambda function says that can't find the file _index.js_.

In [#3864](https://github.com/aws-amplify/amplify-cli/issues/3864#issuecomment-609011456) says something about, but I really don't understand.
